### ISSUE TITLE
Error help

### ISSUE THREAD

**Issue by feijoes** [wezm/deno-rust-wasm#1]
process_begin: CreateProcess(NULL, wasm-bindgen target/wasm32-unknown-unknown/release/feijoes.wasm --target deno --out-dir build, ...) failed.
I just clone the project

**Comment by wezm** [comment]
It looks like wasm-bindgen failed to run. Do you have the dependencies listed in the README installed?

Dependencies

- Rust with wasm32-unknown-unknown target
- Deno
- wasm-bindgen
- make (GNU make or BSD make will work)

**Comment by feijoes** [comment]
Thank you, I was able to resolve the problem. It seems that the 'wasm-bindgen' package was not installed correctly, which caused the issue.

**Comment by wezm** [comment]
Excellent, glad you were able to solve the problem.
